### ISSUE TITLE
pthread PR merge causes MiBench/automotive/bitcount benchmark to fail

### ISSUE THREAD

**Issue by Emoun** [t-crest/patmos-newlib#3]
The recent #2 merge has caused the patmos-benchmarks/MiBench/automotive/bitcount to fail to compile when [run through Travis](https://travis-ci.com/github/t-crest/patmos-llvm/jobs/336002821). The error says:

```
/home/travis/build/t-crest/patmos-llvm/build/bench/MiBench/automotive/bitcount/bitcnts.c:79:35: error: 
      use of undeclared identifier 'CLOCKS_PER_SEC'
    ct = (stop - start) / (double)CLOCKS_PER_SEC;
                                  ^
3 warnings and 1 error generated.
```
I can confirm that this error also happens on my machine. Additionally, reverting the Travis build to the commit before the PR merge [allows it to succeed](https://travis-ci.com/github/t-crest/patmos-llvm/builds/168062721).

CC @torurstrom @schoeberl

**Comment by torurstrom** [comment]
Should be fixed with commit 4c149a5
